# Generated by Django 4.2.6 on 2023-10-25 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_files_fyles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fyles',
            name='file',
        ),
        migrations.RemoveField(
            model_name='fyles',
            name='file_size',
        ),
    ]
